name: Deploy Theme to CPI Test Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SFTP Deploy
        uses: garygrossgarten/github-action-sftp@0.5.0
        with:
          host: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 10397
          localDir: .
          remoteDir: /html/wp-content/themes/xalink-theme/