name: Deploy Theme to CPI Test Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy via SSH/SFTP
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SFTP_KEY }}
          REMOTE_HOST: ${{ secrets.SFTP_SERVER }}
          REMOTE_USER: ${{ secrets.SFTP_USERNAME }}
          REMOTE_PORT: "10398"
          TARGET: "/html/wp-content/themes/xalink-theme/"